<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.11.0" name="Sprites" class="Sprite" tilewidth="12" tileheight="12" tilecount="120" columns="10">
 <image source="spritesheet.png" width="120" height="144"/>
 <tile id="0" type="error"/>
 <tile id="1" type="bell"/>
 <tile id="2" type="crumbler"/>
 <tile id="3" type="crumbling_1"/>
 <tile id="4" type="crumbling_2"/>
 <tile id="5" type="crumbling_3"/>
 <tile id="6" type="bubble_1"/>
 <tile id="7" type="bubble_2"/>
 <tile id="10" type="panda_doll"/>
 <tile id="11" type="panda_wallslide"/>
 <tile id="12" type="panda_ascend"/>
 <tile id="13" type="panda_descend"/>
 <tile id="14" type="bubble_pop_1"/>
 <tile id="15" type="bubble_pop_2"/>
 <tile id="16" type="bubble_pop_3"/>
 <tile id="17" type="bubble_3"/>
 <tile id="20" type="panda_stand"/>
 <tile id="21" type="panda_run_1"/>
 <tile id="22" type="panda_run_2"/>
 <tile id="23" type="panda_run_3"/>
 <tile id="24" type="ball_blue"/>
 <tile id="25" type="ball_white"/>
 <tile id="26" type="ball_brown"/>
 <tile id="27" type="ball_red"/>
 <tile id="30" type="panda_swim_1"/>
 <tile id="31" type="panda_swim_2"/>
 <tile id="32" type="panda_swim_down"/>
 <tile id="33" type="panda_skid"/>
 <tile id="34" type="grapes"/>
 <tile id="35" type="strawberry"/>
 <tile id="36" type="orange"/>
 <tile id="37" type="kiwi"/>
 <tile id="40" type="redd_doll"/>
 <tile id="41" type="redd_wallslide"/>
 <tile id="42" type="redd_ascend"/>
 <tile id="43" type="redd_descend"/>
 <tile id="44" type="cherry"/>
 <tile id="45" type="banana"/>
 <tile id="46" type="apple"/>
 <tile id="47" type="watermelon"/>
 <tile id="50" type="redd_stand"/>
 <tile id="51" type="redd_run_1"/>
 <tile id="52" type="redd_run_2"/>
 <tile id="53" type="redd_run_3"/>
 <tile id="54" type="flashbulb_1"/>
 <tile id="55" type="flashbulb_2"/>
 <tile id="56" type="flashbulb_3"/>
 <tile id="57" type="flashbulb_4"/>
 <tile id="58" type="bonus_1_10"/>
 <tile id="59" type="bonus_2_10"/>
 <tile id="60" type="redd_swim_1"/>
 <tile id="61" type="redd_swim_2"/>
 <tile id="62" type="redd_swim_down"/>
 <tile id="63" type="redd_skid"/>
 <tile id="64" type="coin_1"/>
 <tile id="65" type="coin_2"/>
 <tile id="66" type="coin_3"/>
 <tile id="67" type="coin_4"/>
 <tile id="68" type="bonus_3_10"/>
 <tile id="69" type="bonus_4_10"/>
 <tile id="70" type="sparkle_small"/>
 <tile id="71" type="sparkle_big"/>
 <tile id="72" type="chest_closed"/>
 <tile id="73" type="chest_open"/>
 <tile id="74" type="key"/>
 <tile id="75" type="flagpole_silver"/>
 <tile id="76" type="flag_blue_1"/>
 <tile id="77" type="flag_blue_2"/>
 <tile id="78" type="bonus_5_10"/>
 <tile id="79" type="bonus_6_10"/>
 <tile id="80" type="spring_down"/>
 <tile id="81" type="spring_mid"/>
 <tile id="82" type="spring_up"/>
 <tile id="83" type="ruby"/>
 <tile id="84" type="lockbox"/>
 <tile id="85" type="flagpole_gold"/>
 <tile id="86" type="flag_red_1"/>
 <tile id="87" type="flag_red_2"/>
 <tile id="88" type="bonus_7_10"/>
 <tile id="89" type="bonus_8_10"/>
 <tile id="90" type="bonus_1"/>
 <tile id="91" type="bonus_2"/>
 <tile id="92" type="bonus_3"/>
 <tile id="93" type="bonus_4"/>
 <tile id="94" type="bonus_5"/>
 <tile id="95" type="score_left"/>
 <tile id="96" type="score_mid"/>
 <tile id="97" type="score_right"/>
 <tile id="98" type="bonus_9_10"/>
 <tile id="99" type="bonus_10_10"/>
 <tile id="100" type="lamp_unlit"/>
 <tile id="101" type="lamp_green"/>
 <tile id="102" type="lamp_amber"/>
 <tile id="103" type="lamp_red"/>
 <tile id="104" type="silver_coin_1"/>
 <tile id="105" type="silver_coin_2"/>
 <tile id="106" type="silver_coin_3"/>
 <tile id="107" type="silver_coin_4"/>
 <tile id="108" type="small_ball_yellow"/>
 <tile id="109" type="small_ball_red"/>
 <tile id="110" type="bonus_blank"/>
 <tile id="111" type="splash_1"/>
 <tile id="112" type="splash_2"/>
 <tile id="113" type="splash_3"/>
 <tile id="114" type="balloon_blue"/>
 <tile id="115" type="balloon_green"/>
 <tile id="116" type="balloon_red"/>
 <tile id="117" type="small_ball_blue"/>
 <tile id="118" type="small_ball_orange"/>
 <tile id="119" type="small_ball_green"/>
</tileset>
